-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "LogType" ADD VALUE 'EMAIL_WEBHOOK_RECEIVED';
ALTER TYPE "LogType" ADD VALUE 'FILE_UPLOADED';
ALTER TYPE "LogType" ADD VALUE 'EVENT_CREATED';
ALTER TYPE "LogType" ADD VALUE 'EVENT_MODIFIED';
ALTER TYPE "LogType" ADD VALUE 'EVENT_DELETED';
ALTER TYPE "LogType" ADD VALUE 'CAMPAIGN_CREATED';
ALTER TYPE "LogType" ADD VALUE 'CAMPAIGN_MODIFIED';
ALTER TYPE "LogType" ADD VALUE 'CAMPAIGN_DELETED';
ALTER TYPE "LogType" ADD VALUE 'FORM_FIELD_CREATED';
ALTER TYPE "LogType" ADD VALUE 'FORM_FIELD_MODIFIED';
ALTER TYPE "LogType" ADD VALUE 'FORM_FIELD_DELETED';
ALTER TYPE "LogType" ADD VALUE 'FORM_RESPONSE_CREATED';
ALTER TYPE "LogType" ADD VALUE 'FORM_RESPONSE_MODIFIED';
ALTER TYPE "LogType" ADD VALUE 'FORM_RESPONSE_DELETED';
ALTER TYPE "LogType" ADD VALUE 'LOCATION_CREATED';
ALTER TYPE "LogType" ADD VALUE 'LOCATION_MODIFIED';
ALTER TYPE "LogType" ADD VALUE 'LOCATION_DELETED';
ALTER TYPE "LogType" ADD VALUE 'JOB_CREATED';
ALTER TYPE "LogType" ADD VALUE 'JOB_MODIFIED';
ALTER TYPE "LogType" ADD VALUE 'JOB_DELETED';
ALTER TYPE "LogType" ADD VALUE 'SHIFT_CREATED';
ALTER TYPE "LogType" ADD VALUE 'SHIFT_MODIFIED';
ALTER TYPE "LogType" ADD VALUE 'SHIFT_DELETED';
