name = "cron-webhook"
main = "src/index.js"
compatibility_date = "2025-07-06"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[triggers]
crons = [
  "0 * * * *"      # Runs hourly
]